# Generated by Django 3.0.8 on 2020-09-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userroute', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userroute',
            old_name='Round_about',
            new_name='dutse_Round_about',
        ),
        migrations.RenameField(
            model_name='userroute',
            old_name='first_gate',
            new_name='dutse_first_gate',
        ),
        migrations.RenameField(
            model_name='userroute',
            old_name='second_gate',
            new_name='dutse_second_gate',
        ),
    ]
